default: &default
  root_path: app/assets/entrypoints
  entry_paths: []
  alias:
    a: '/'
  server:
    port: 4000
  build:
    assetsInlineLimit: 0
    sourcemap: false
development:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-dev
  server:
    host: localhost
    port: 3036
test:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-test
production:
  <<: *default
