# Vite 默认配置
default: &default

  source_path: app/packs
  
  watchAdditionalPaths: []
  server:
    port: 4000
development:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-dev
  server:
    port: 3036
test:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-test
