# Vite 默认配置
default: &default
  root_path: app/assets/entrypoints
  public_root_path: public
  public_output_path: vites
development:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-dev
  server:
    host: localhost
    port: 4000
test:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-test
production:
  <<: *default
