# Vite 默认配置
default: &default
  source_path: app/packs
  source_entry_path: javascripts
  public_root_path: public
  public_output_path: vites
  watchAdditionalPaths: []
development:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-dev
  server:
    host: localhost
    port: 4000
test:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-test
production:
  <<: *default
