default: &default
  source_path: app/packs
  include: []
  server:
    port: 4000
development:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-dev
  server:
    host: localhost
    port: 3036
test:
  <<: *default
  autoBuild: true
  publicOutputDir: vite-test
